### ISSUE TITLE
Spec numbers are shifted by 1.

### ISSUE THREAD

**Issue by UnknownFME** [boltgolt/boltobserv#94] opened 2024-01-07 17:42 UTC
All the radar numbers are shifted in the wrong direction by 1. If it says 0 on radar the actual slot is 1 and so on all the way through.

So teams are now divided up like this visuall:

0-4 and 5-9

Though the keys are still the same

1-5 and 6-0

**Comment by Schadelbohrer** [comment] 2024-01-10 19:01
I have the same problem.

**Comment by Kerovski** [comment] 2024-01-11 11:57
Same problem. I wanted to use this and to support this project, but it just not working.

**Comment by boltgolt** [comment] 2024-01-11 12:06
So in short, [this merged PR](https://github.com/boltgolt/boltobserv/pull/91) would fix if i have time to get a release together, wouldn't it? 

(@Kerovski "support this project", yeah right)

**Comment by Kerovski** [comment] 2024-01-11 13:54
@boltgolt I'm a bit uncertain about your message, but it seems like you're questioning my willingness to donate to the project's creator. That's alright; you don't really know me, so I understand the doubt. Just try not to jump to conclusions too quickly.

I think the radar is impressive, and I did give it a try. Unfortunately, I couldn't use it due to a bug with the numbers. It's worth acknowledging that many individuals are putting in hard work to release various things for free. Every now and then, we can contribute with a donation to support their efforts. God bless you all.

**Comment by fyflo** [comment] 2024-01-30 11:43
The solution to the problem is in this request. [https://github.com/boltgolt/boltobserv/issues/90](url)

**Comment by fyflo** [comment] 2024-04-04 15:06
> @boltgolt Can you share a guesstimate on when this might be released? :-) I use this in combination with the [cs-hud](https://github.com/drweissbrot/cs-hud) and the first player starting at 0 is causing visible confusion for viewers, so would greatly appreciate a release of the fix by @fyflo

@ReneRebsdorf
The application you specified is not associated with the boltobserv application. You need to contact the owner of the application you specified.

**Comment by ReneRebsdorf** [comment] 2024-04-04 18:46
> > @boltgolt Can you share a guesstimate on when this might be released? :-) I use this in combination with the [cs-hud](https://github.com/drweissbrot/cs-hud) and the first player starting at 0 is causing visible confusion for viewers, so would greatly appreciate a release of the fix by @fyflo
> 
> 
> 
> @ReneRebsdorf
> 
> The application you specified is not associated with the boltobserv application. You need to contact the owner of the application you specified.
> 
> 

@fyflo you must have misread my comment
I am asking when the fix you made in January is released in boltobserv, as I see it the latest release is from October 2023, to increment on the radar to fix the offset by one problem as per the radar overlay from boltobserv

**Comment by fyflo** [comment] 2024-04-05 14:26
@ReneRebsdorf 
The owner previously reported that he is currently busy and will fix it when he has time. You can correct the data in this file yourself using any text editor Boltobserv-v1.4.0-win32-x64\resources\app\html\map.html
You can also go to my repository and maybe you will be interested in HUDs for broadcasts.

**Comment by ReneRebsdorf** [comment] 2024-04-06 13:05
Thanks @fyflo  :-)

**Comment by boltgolt** [comment] 2024-06-15 21:12
Should finally be fixed by 1.5.0! Sorry for the wait everyone, i forgot to actually release it

**Closed by boltgolt** 2024-06-15 21:12 UTC
